[package]
name = "faucon"
version = "0.1.0"
authors = ["Valentin B. <valentin.be@protonmail.com>"]
description = "Comprehensive tooling suite for NVIDIA Falcon microprocessors"
license = "ISC"
homepage = "https://github.com/vbe0201/faucon"
edition = "2021"

[dependencies]
